### GET request to example server
POST localhost:1234/register
Content-Type: application/json

{
  "username": "kiramira",
  "password_hash": "qwq233383"
}
###
POST localhost:1234/login
Content-Type: application/json

{
  "username": "kiramira",
  "password_hash": "qwq233383"

}

###
POST localhost:1234/api/v1/user/logout
Content-Type: application/json
Authorization: Bearer {{auth_key}}

###
POST localhost:1234/api/v1/session
Content-Type: application/json
Authorization: Bearer {{auth_key}}

{
  "conv_type": 1,
  "owner_id": 1
}

###
GET localhost:1234/api/v1/session
Content-Type: application/json
Authorization: Bearer {{auth_key}}

{
  "page": 1,
  "page_size": 5,
  "user_id": 1
}

###
POST http://localhost:1234/api/v1/message
Content-Type: application/json
Authorization: Bearer {{auth_key}}

{

  "sender_id": 1,
  "content": "一键启动所有hadoop集群",
  "msg_type": 1,
  "conv_id": 1,
  "receiver_type": 1
}

### conv_id is optional ,json should instead of form
GET localhost:1234/api/v1/message
Content-Type: application/json
Authorization: Bearer {{auth_key}}

{
  "page": 1,
  "page_size": 5,
  "user_id": 1,
  "conv_id": 1
}

###


